   sonar.projectKey=SC-Student-System
   sonar.sources=.
   sonar.exclusions=**/node_modules/**,**/venv/**,**/__pycache__/**
   sonar.host.url=http://localhost:9090
   sonar.token=sqp_e85c296f9adc35ab044b2933226e80d77f98528e